### ISSUE TITLE
Converting uniprot ID to Entrezid using org.Cauris.eg.db

### ISSUE THREAD

**Issue by okendojo** [lakhanp1/fungal_resources#1]
I am trying to use you `org.Cauris.eg.db` package do to enrichment analysis. I need to convert `Uniprot ID` to `ENTREZID` using the following `clusterProfiler` command. `gene.df <- bitr(gene, fromType = "UNIPROT", toType = "ENTREZID",OrgDb = org.Cauris.eg.db) ; dim(gene.df)` but I am getting the following error prompt: `Error in bitr(gene, fromType = "UNIPROT", toType = "ENTREZID", OrgDb = org.Cauris.eg.db) : 'fromType' should be one of BLASTX_SUMMARY, CGD_ORTHOLOG, DESCRIPTION, EVIDENCE, EVIDENCEALL, GID, GO, GOALL, ONTOLOGY, ONTOLOGYALL, ORTHOLOG_SOURCE, PFAM_ID, PFAM_TERM, POSITION, STRAND.` Could you add the Uniprot information in this package?

**Comment by lakhanp1** [comment]
Hi Javan,
Sorry for the late reply. May I know which C. auris assembly you are using for your analysis, B8441 or B11221_V1? The current org.db is based on B8441 assembly. I am working on mapping the Entrez and UniProt IDs to genes from this. Meanwhile, if you already have this mapped list, can you please share this with me? Then I can quickly add those two columns.
Another quicker option is to use `EuPathDB` package from `BioConductor` to generate `org.db` for any organism listed on `FungiDb`. Please refer to the [EupathDB](https://bioconductor.org/packages/release/data/annotation/vignettes/EuPathDB/inst/doc/EuPathDB.html) manual for details.

**Comment by okendojo** [comment]
@lakhanp1 thanks for your response. I used goa `ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/proteomes/4144447.[_auris_B8441.goa` to do the enrichment analysis. I downloaded the goa file from [https://www.ebi.ac.uk/GOA/proteomes](www.ebi.ac.uk). I can share the script I used if you may want to try it out.

**Comment by lakhanp1** [comment]
Hi Javan,
Thank you for sharing the GOA file link. I have added the `UNIPROT` column to the `org.db`.
